In [1]:
import sqlite3

connection = sqlite3.connect('6.db')
cursor = connection.cursor()

# ------------------ Professors Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS professors(
    ProfessorID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    DateOfBirth DATE NOT NULL,
    PhoneNumber TEXT UNIQUE NOT NULL,
    OfficeLocation TEXT NOT NULL
)
''')

# ------------------ Colleges Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS colleges(
    CollegeID INTEGER PRIMARY KEY AUTOINCREMENT,
    CollegeName TEXT NOT NULL,
    DeanID INTEGER,
    FOREIGN KEY (DeanID) REFERENCES professors(ProfessorID)
)
''')

# ------------------ Departments Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS departments(
    DeptID INTEGER PRIMARY KEY AUTOINCREMENT,
    DeptName TEXT NOT NULL,
    CollegeID INTEGER NOT NULL,
    DeptHeadID INTEGER NOT NULL,
    FOREIGN KEY (CollegeID) REFERENCES colleges(CollegeID),
    FOREIGN KEY (DeptHeadID) REFERENCES professors(ProfessorID)
)
''')

# ------------------ Students Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS students(
    StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    DateOfBirth DATE NOT NULL,
    Gender TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    PhoneNumber TEXT UNIQUE NOT NULL,
    EnrollmentStatus TEXT NOT NULL,
    MajorDeptID INTEGER NOT NULL,
    MinorDeptID INTEGER,
    FOREIGN KEY (MajorDeptID) REFERENCES departments(DeptID),
    FOREIGN KEY (MinorDeptID) REFERENCES departments(DeptID)
)
''')

# ------------------ Staff Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS staff(
    StaffID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Position TEXT NOT NULL,
    Salary FLOAT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    PhoneNumber TEXT UNIQUE NOT NULL,
    EmploymentStatus TEXT NOT NULL
)
''')

# ------------------ Courses Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS courses(
    CourseID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourseName TEXT NOT NULL,
    CourseCode TEXT UNIQUE NOT NULL,
    DeptID INTEGER NOT NULL,
    Credits INTEGER NOT NULL,
    Description TEXT,
    FOREIGN KEY (DeptID) REFERENCES departments(DeptID)
)
''')

# ------------------ Classrooms Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS classrooms(
    RoomID INTEGER PRIMARY KEY AUTOINCREMENT,
    BuildingName TEXT NOT NULL,
    RoomNumber TEXT NOT NULL,
    Capacity INTEGER NOT NULL,
    RoomType TEXT NOT NULL
)
''')

# ------------------ Course Schedule Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS courseSchedule(
    ScheduleID INTEGER PRIMARY KEY AUTOINCREMENT,
    CourseID INTEGER NOT NULL,
    RoomID INTEGER NOT NULL,
    ProfessorID INTEGER NOT NULL,
    DayOfWeek TEXT NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    Semester TEXT NOT NULL,
    Year INTEGER NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES courses(CourseID),
    FOREIGN KEY (RoomID) REFERENCES classrooms(RoomID),
    FOREIGN KEY (ProfessorID) REFERENCES professors(ProfessorID)
)
''')

# ------------------ Enrollments Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS enrollments(
    EnrollmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL,
    CourseID INTEGER NOT NULL,
    Semester TEXT NOT NULL,
    Year INTEGER NOT NULL,
    Grade TEXT,
    FOREIGN KEY (StudentID) REFERENCES students(StudentID),
    FOREIGN KEY (CourseID) REFERENCES courses(CourseID)
)
''')

# ------------------ Tuition and Fees Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS tuitionAndFees(
    FeeID INTEGER PRIMARY KEY AUTOINCREMENT,
    FeeName TEXT NOT NULL,
    Amount INTEGER NOT NULL,
    AcademicYear INTEGER NOT NULL,
    FeeType TEXT NOT NULL
)
''')

# ------------------ Student Accounts Table ------------------
cursor.execute('''
CREATE TABLE IF NOT EXISTS studentAccounts(
    AccountID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL,
    FeeID INTEGER NOT NULL,
    AmountDue FLOAT,
    DueDate DATE NOT NULL,
    Status TEXT NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES students(StudentID),
    FOREIGN KEY (FeeID) REFERENCES tuitionAndFees(FeeID)
)
''')

# Commit and close
connection.commit()
connection.close()

In [ ]:
# Aidens Block
import sqlite3
connection= sqlite3.connect('Aiden.db')
cursor = connection.cursor()
# ------------------ feePayments table ------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS feePayments(
               PaymentID INTEGER PRIMARY KEY AUTOINCREMENT,
               AccountID TEXT NOT NULL,
               PaymentDate DATE NOT NULL DEFAULT (DATE('now')),
               AmountPaid REAL NOT NULL DEFAULT 0.00,
               PaymentMethod TEXT NOT NULL,
               FOREIGN KEY (AccountID) REFERENCES studentAccounts(AccountID)
               )''')
# ------------------ scholarships table ------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS scholarships(
               ScholarshipID INTEGER PRIMARY KEY AUTOINCREMENT,
               ScholarshipName TEXT NOT NULL,
               Amount REAL NOT NULL,
               EligibilityCriteria TEXT NOT NULL)
''')
# ------------------ researchProjects table ------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS researchProjects(
               ProjectID INTEGER PRIMARY KEY AUTOINCREMENT,
               ProjectName TEXT NOT NULL,
               DeptID INTEGER NOT NULL,
               Budget REAL NOT NULL,
               StartDate DATE NOT NULL DEFAULT (DATE('now')),
               EndDate DATE,
               PrincipalInvestigatorID INTEGER NOT NULL,
               FOREIGN KEY (DeptID) REFERENCES departments(DeptID),
               FOREIGN KEY (PrincipalInvestigatorID) REFERENCES professors(ProfessorID) 
               )
               ''')
 # ------------------ publications table ------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS publications(
               PublicationID INTEGER PRIMARY KEY AUTOINCREMENT,
               Title TEXT NOT NULL,
               PublicationDate DATE NOT NULL DEFAULT (DATE('now')),
               JournalName TEXT NOT NULL,
               ProjectID INTEGER NOT NULL,
               FOREIGN KEY (ProjectID) REFERENCES researchProjects(ProjectID)
               )''')
# ------------------ libraries table ------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS libraries(
               LibraryID INTEGER PRIMARY KEY AUTOINCREMENT,
               LibraryName TEXT NOT NULL,
               Location TEXT NOT NULL,
               OperatingHours TEXT NOT NULL)''')




# ------------------ Commit and close ------------------
connection.commit()
cursor.close()

In [1]:
#Sofie's block

import sqlite3

connection = sqlite3.connect('sofiev2.db')
cursor = connection.cursor()


# --------------------ATHLETE DATABASE--------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS athletes (
               AthleteID INTEGER PRIMARY KEY AUTOINCREMENT,
               StudentID INTEGER NOT NULL,
               FOREIGN KEY (StudentID) REFERENCES students(StudentID),
               SportID INTEGER NOT NULL,
               FOREIGN KEY (SportID) REFERENCES sports(SportID),
               EligibilityStatus TEXT NOT NULL
                )''')

cursor.execute('''CREATE TABLE IF NOT EXISTS addresses (
               AddressID INTEGER PRIMARY KEY AUTOINCREMENT,
               StreetAddress TEXT NOT NULL,
               City TEXT NOT NULL,
               State TEXT NOT NULL,
               ZipCode INTEGER NOT NULL
               )''')

cursor.execute('''CREATE TABLE IF NOT EXISTS studentAddresses (
               StudentID INTEGER NOT NULL,
               AddressID INTEGER NOT NULL,
               PRIMARY KEY (StudentID, AddressID),
               FOREIGN KEY (StudentID) REFERENCES students(StudentID),
               FOREIGN KEY (AddressID) REFERENCES addresses(AddressID),
               AddressType TEXT NOT NULL
               )''')

cursor.execute('''CREATE TABLE IF NOT EXISTS professorAddresses (
               ProfessorID INTEGER NOT NULL AUTOINCREMENT,
               AddressID INTEGER NOT NULL,
               PRIMARY KEY (ProfessorID, AddressID),
               FOREIGN KEY (ProfessorID) REFERENCES professors(ProfessorID),
               FOREIGN KEY (AddressID) REFERENCES addresses(AddressID),
               AddressType TEXT NOT NULL
               )''')


# --------------------MEDICAL RECORDS DATABASE--------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS medicalRecords (
               RecordID INTEGER PRIMARY KEY AUTOINCREMENT,
               StudentID INTEGER NOT NULL,
               FOREIGN KEY (StudentID) REFERENCES students(StudentID),
               MedicalHistory TEXT NOT NULL,
               LastCheckUpDate DATE NOT NULL,
               Allergies TEXT,
               )''')


# --------------------ALUMNI DATABASE--------------------
cursor.execute('''CREATE TABLE IF NOT EXISTS alumni (
               AlumniID INTEGER PRIMARY KEY AUTOINCREMENT,
               StudentID INTEGER NOT NULL,
               FOREIGN KEY (StudentID) REFERENCES students(StudentID),
               GraduationYear INTEGER NOT NULL,
               Degree TEXT NOT NULL,
               ContactEmail TEXT NOT NULL UNIQUE
               )''')

cursor.execute('''CREATE TABLE IF NOT EXISTS registrarOffice (
               OfficeID INTEGER PRIMARY KEY AUTOINCREMENT,
               OfficeName TEXT NOT NULL,
               Location TEXT NOT NULL,
               ContactInfo TEXT NOT NULL UNIQUE
               )''')

cursor.execute('''CREATE TABLE IF NOT EXISTS officeStaff (
                OfficeID INTEGER NOT NULL,
                StaffID INTEGER NOT NULL,
                PRIMARY KEY (OfficeID, StaffID),
                FOREIGN KEY (OfficeID) REFERENCES registrarOffice(OfficeID),
                FOREIGN KEY (StaffID) REFERENCES staff(StaffID)
               )''')


# ------------------ Commit and close ------------------
connection.commit()
cursor.close()

OperationalError: near "SportID": syntax error